---
title: ""
output: github_document

---

```{r}
library(tidyverse)
library(rvest)
library(httr)

```

IMPORT NSDUH DATA
```{r}
nsduh_url="http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_url=
  read_html(nsduh_url)
```


```{r}
marj_use_df =
  nsduh_url |> 
  html_table() |> 
  first() |> 
  slice(-1)
```


Import Star Wars...

```{r}
swm_url=
  "https://www.imdb.com/list/ls070150896/"

swm_url=
  read_html(swm_url)
```

```{r}
title_vec = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

gross_rev_vec = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".runtime") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## APIs

Get water data from NYC

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

BRFSS Data

```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
```

Try it now!

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()

poke$name
```

